version: '3.8'

services:
  api:
    image: thiskk/ms-storage:workshop2.0

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: 'bookstore'
      MYSQL_USER: 'admin_db'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
